CREATE DATABASE ESCOLA;


CREATE TABLE ALUNO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    ENDERECO VARCHAR(255)
);


CREATE TABLE CURSO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CARGA_HORARIA INT
);

CREATE TABLE PROFESSOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    DEPARTAMENTO VARCHAR(100)
);

CREATE TABLE MATRICULA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ALUNO_ID INT,
    CURSO_ID INT,
    DATA_MATRICULA DATE,
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ID),
    FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID)
);

--insert

INSERT INTO ALUNO (NOME, EMAIL, ENDERECO) VALUES ('João Silva', 'joao.silva@example.com', 'Rua A, 123');
INSERT INTO ALUNO (NOME, EMAIL, ENDERECO) VALUES ('Maria Oliveira', 'maria.oliveira@example.com', 'Avenida B, 456');


INSERT INTO CURSO (NOME, CARGA_HORARIA) VALUES ('Matemática', 60);
INSERT INTO CURSO (NOME, CARGA_HORARIA) VALUES ('História', 40);

INSERT INTO PROFESSOR (NOME, EMAIL, DEPARTAMENTO) VALUES ('Carlos Pereira', 'carlos.pereira@example.com', 'Matemática');
INSERT INTO PROFESSOR (NOME, EMAIL, DEPARTAMENTO) VALUES ('Ana Costa', 'ana.costa@example.com', 'História');

INSERT INTO MATRICULA (ALUNO_ID, CURSO_ID, DATA_MATRICULA) VALUES (1, 1, '2024-01-15');
INSERT INTO MATRICULA (ALUNO_ID, CURSO_ID, DATA_MATRICULA) VALUES (2, 2, '2024-02-10');

--Consultas com join
SELECT ALUNO.NOME AS Aluno, CURSO.NOME AS Curso, MATRICULA.DATA_MATRICULA
FROM MATRICULA
JOIN ALUNO ON MATRICULA.ALUNO_ID = ALUNO.ID
JOIN CURSO ON MATRICULA.CURSO_ID = CURSO.ID;


SELECT CURSO.NOME AS Curso, PROFESSOR.NOME AS Professor, COUNT(MATRICULA.ALUNO_ID) AS Numero_Alunos
FROM CURSO
JOIN MATRICULA ON CURSO.ID = MATRICULA.CURSO_ID
JOIN PROFESSOR ON CURSO.ID = PROFESSOR.ID
GROUP BY CURSO.NOME, PROFESSOR.NOME;


